### ISSUE TITLE
[feature request] Make it possible to use a texture to 3d view

### ISSUE THREAD

**Issue by milasudril** [milasudril/texpainter#42]
# Summary
Add a selector to use RGBA data as a texture.

# Motivation
When generating landscapes, the terrain data can be used to generate a suitable texture. Make it possible to preview a generated texture when previewing terrain.

# Proposed solution
A vertical panel to the left the actual view would do. Note: This panel may also host other widgets for camera control. 

# Roadmap

- [ ] Make sure it is possible to render from more than one node
- [ ] Add a 3d view control panel
- [ ] Add texture sampler to shader
- [ ] Add functionality to upload texture from CPU to GPU
